name: Path Filtering
description: Filter paths based on git diff rules
author: lostick

inputs:
  config_file:
    description: Diff rules file path
    default: .github/rules.yml
    required: true
  base_ref:
    description: Base branch to compare to
    default: main
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: list
  color: gray-dark
