name: main

on:
  push:
    branches:
    - main

jobs:
  # test npm scripts
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        npm install
        npm run all
