name: pr

on:
  pull_request:
    types:
    - synchronize
    - opened
    - reopened
    - ready_for_review
  push:
    branches:
    - '!main'

jobs:
  # test npm scripts
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 100
    - run: |
        npm install
        npm run all
  # test against main branch
  test-default-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 100
    - uses: ./
    - name: Ensure a change has been detected
      run: |
        [ "${DIFF_DETECTED}" == 'true' ] || exit 1
  # test against a base branch that's not main
  test-non-default-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 100
    - uses: ./
      with:
        base_ref: add-base-ref-input-base-test
    - name: Ensure a change has been detected
      run: |
        [ "${DIFF_DETECTED}" == 'true' ] || exit 1
  # test with custom file that returns a diff
  test-diff-detected:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 100
    - uses: ./
      with:
        config_file: __tests__/rules-match-all.yml
    - name: Ensure a change has been detected
      run: |
        [ "${DIFF_DETECTED}" == 'true' ] || exit 1
  # test with custom file that returns no diff
  test-no-diff-detected:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 100
    - uses: ./
      with:
        config_file: __tests__/rules-no-diff-detected.yml
    - name: Ensure no change has been detected
      run: |
        [ "${DIFF_DETECTED}" == 'false' ] || exit 1
